In [2]:
from sklearn.cluster import AffinityPropagation
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Moscow_dataSet.csv', index_col=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3502 entries, 0 to 3501
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   floor         3502 non-null   int64
 1   count_floors  3502 non-null   int64
 2   rooms         3502 non-null   int64
 3   square        3502 non-null   float64
 4   district      3502 non-null   int64
 5   price         3502 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 164.3 KB

In [4]:
AP = AffinityPropagation(damping=0.9, random_state=17).fit(df)
AP

AffinityPropagation(damping=0.9, random_state=17)

In [5]:
l = []
X = AP.labels_
for i in X:
    if i not in l:
        l.append(i)
print(min(l), max(l), '\n', l, '\n', sorted(l))

0 34
 [30, 34, 2, 31, 27, 10, 12, 29, 6, 23, 7, 21, 9, 8, 25, 0, 11, 26, 5, 3, 4, 22, 33, 32, 28, 1, 13, 16, 20, 15, 14, 17, 24, 18, 19]
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]

In [6]:
ds = pd.read_csv('dataset.csv', index_col=False, names=['underground', 'length', 'latitude', 'floorscount', 'materialtype', 'buildyear', 'kitchenarea', 'roomscount', 'id', 'totalArea', 'offerType', 'floornumber', 'livingArea', 'price'], encoding='utf-8', delimiter=';')

In [7]:
ds.isna().sum()

underground       0
length            0
latitude          0
floorscount       0
materialtype     97
buildyear       703
kitchenarea     171
roomscount        0
id                0
totalArea         0
offerType         0
floornumber       0
livingArea      271
price             0
dtype: int64

In [8]:
ds = ds.drop(['buildyear'],axis=1)
ds

,underground,length,latitude,floorscount,materialtype,kitchenarea,roomscount,id,totalArea,offerType,floornumber,livingArea,price
0,Авиамоторная,37.741785,55.736599,45,monolith,14.9,2,296820605,37.5,flat,20,13.2,14750536
1,Авиамоторная,37.735153,55.754122,5,monolith,3.0,2,301280744,25.9,flat,4,22.0,7690000
2,Авиамоторная,37.743276,55.736854,37,monolith,9.7,1,296502502,35.0,flat,2,12.7,13215071
3,Авиамоторная,37.700595,55.749435,28,monolith,10.0,1,301175786,34.0,flat,6,20.0,18990000
4,Авиамоторная,37.696511,55.753244,11,monolith,13.2,1,301392165,38.9,flat,3,12.7,12436330
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402,Академическая,37.596704,55.686127,12,block,6.4,2,301278643,39.0,flat,10,24.0,16000000
1403,Академическая,37.558158,55.696098,8,stalin,9.5,2,300799962,67.4,flat,7,40.6,26990000
1404,Академическая,37.577364,55.683818,17,panel,9.0,1,300783085,36.0,flat,2,15.0,15950000
1405,Академическая,37.546525,55.693145,8,brick,8.7,2,300139258,60.0,flat,1,NaN,18570000
1406,Академическая,37.560188,55.691070,11,brick,10.0,2,300684389,54.2,flat,10,NaN,19800000

In [9]:
dst = ds.dropna(axis=0)
dst.isna().sum()

underground     0
length          0
latitude        0
floorscount     0
materialtype    0
kitchenarea     0
roomscount      0
id              0
totalArea       0
offerType       0
floornumber     0
livingArea      0
price           0
dtype: int64

In [10]:
dst.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1057 entries, 0 to 1404
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   underground   1057 non-null   object
 1   length        1057 non-null   float64
 2   latitude      1057 non-null   float64
 3   floorscount   1057 non-null   int64
 4   materialtype  1057 non-null   object
 5   kitchenarea   1057 non-null   float64
 6   roomscount    1057 non-null   int64
 7   id            1057 non-null   int64
 8   totalArea     1057 non-null   float64
 9   offerType     1057 non-null   object
 10  floornumber   1057 non-null   int64
 11  livingArea    1057 non-null   float64
 12  price         1057 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 115.6+ KB

In [11]:
dst

,underground,length,latitude,floorscount,materialtype,kitchenarea,roomscount,id,totalArea,offerType,floornumber,livingArea,price
0,Авиамоторная,37.741785,55.736599,45,monolith,14.9,2,296820605,37.5,flat,20,13.2,14750536
1,Авиамоторная,37.735153,55.754122,5,monolith,3.0,2,301280744,25.9,flat,4,22.0,7690000
2,Авиамоторная,37.743276,55.736854,37,monolith,9.7,1,296502502,35.0,flat,2,12.7,13215071
3,Авиамоторная,37.700595,55.749435,28,monolith,10.0,1,301175786,34.0,flat,6,20.0,18990000
4,Авиамоторная,37.696511,55.753244,11,monolith,13.2,1,301392165,38.9,flat,3,12.7,12436330
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400,Академическая,37.597055,55.687193,9,brick,6.1,1,297903698,32.0,flat,6,18.1,11500000
1401,Академическая,37.582008,55.703936,5,block,6.0,2,296086761,42.4,flat,2,26.3,14300000
1402,Академическая,37.596704,55.686127,12,block,6.4,2,301278643,39.0,flat,10,24.0,16000000
1403,Академическая,37.558158,55.696098,8,stalin,9.5,2,300799962,67.4,flat,7,40.6,26990000
1404,Академическая,37.577364,55.683818,17,panel,9.0,1,300783085,36.0,flat,2,15.0,15950000

In [12]:
dst = dst.reset_index()
dst

,index,underground,length,latitude,floorscount,materialtype,kitchenarea,roomscount,id,totalArea,offerType,floornumber,livingArea,price
0,0,Авиамоторная,37.741785,55.736599,45,monolith,14.9,2,296820605,37.5,flat,20,13.2,14750536
1,1,Авиамоторная,37.735153,55.754122,5,monolith,3.0,2,301280744,25.9,flat,4,22.0,7690000
2,2,Авиамоторная,37.743276,55.736854,37,monolith,9.7,1,296502502,35.0,flat,2,12.7,13215071
3,3,Авиамоторная,37.700595,55.749435,28,monolith,10.0,1,301175786,34.0,flat,6,20.0,18990000
4,4,Авиамоторная,37.696511,55.753244,11,monolith,13.2,1,301392165,38.9,flat,3,12.7,12436330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,1400,Академическая,37.597055,55.687193,9,brick,6.1,1,297903698,32.0,flat,6,18.1,11500000
1053,1401,Академическая,37.582008,55.703936,5,block,6.0,2,296086761,42.4,flat,2,26.3,14300000
1054,1402,Академическая,37.596704,55.686127,12,block,6.4,2,301278643,39.0,flat,10,24.0,16000000
1055,1403,Академическая,37.558158,55.696098,8,stalin,9.5,2,300799962,67.4,flat,7,40.6,26990000
1056,1404,Академическая,37.577364,55.683818,17,panel,9.0,1,300783085,36.0,flat,2,15.0,15950000

In [13]:
metrostation = []
mtypes = []
offertype = []
for i in dst['underground']: metrostation.append(i) if i not in metrostation else i
for i in dst['materialtype']: mtypes.append(i) if i not in mtypes else i
for i in dst['offerType']: offertype.append(i) if i not in offertype else i

print(f"{metrostation}\n{mtypes}\n{offertype}")

['Авиамоторная', 'Быковское', 'Автозаводская', 'Академическая']
['monolith', 'brick', 'block', 'panel', 'monolithBrick', 'stalin']
['flat']

In [14]:
dst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1057 entries, 0 to 1056
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         1057 non-null   int64
 1   underground   1057 non-null   object
 2   length        1057 non-null   float64
 3   latitude      1057 non-null   float64
 4   floorscount   1057 non-null   int64
 5   materialtype  1057 non-null   object
 6   kitchenarea   1057 non-null   float64
 7   roomscount    1057 non-null   int64
 8   id            1057 non-null   int64
 9   totalArea     1057 non-null   float64
 10  offerType     1057 non-null   object
 11  floornumber   1057 non-null   int64
 12  livingArea    1057 non-null   float64
 13  price         1057 non-null   int64
dtypes: float64(5), int64(6), object(3)
memory usage: 115.7+ KB

In [15]:
dst = dst.replace({'Авиамоторная': 1, 'Быковское': 2, 'Автозаводская': 3, 'Академическая': 4, 'monolith': 0, 'brick': 5, 'block': 10, 'panel': 15, 'monolithBrick': 20, 'stalin': 25, 'flat': np.NaN})

/var/folders/mz/c85xwc6170v72j1f_tsm0bkh0000gn/T/ipykernel_3798/3006705477.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dst = dst.replace({'Авиамоторная': 1, 'Быковское': 2, 'Автозаводская': 3, 'Академическая': 4, 'monolith': 0, 'brick': 5, 'block': 10, 'panel': 15, 'monolithBrick': 20, 'stalin': 25, 'flat': np.NaN})

In [16]:
dst = dst.dropna(axis=1)
dst.isna().sum()

index           0
underground     0
length          0
latitude        0
floorscount     0
materialtype    0
kitchenarea     0
roomscount      0
id              0
totalArea       0
floornumber     0
livingArea      0
price           0
dtype: int64

In [17]:
dst.head(5)

,index,underground,length,latitude,floorscount,materialtype,kitchenarea,roomscount,id,totalArea,floornumber,livingArea,price
0,0,1,37.741785,55.736599,45,0,14.9,2,296820605,37.5,20,13.2,14750536
1,1,1,37.735153,55.754122,5,0,3.0,2,301280744,25.9,4,22.0,7690000
2,2,1,37.743276,55.736854,37,0,9.7,1,296502502,35.0,2,12.7,13215071
3,3,1,37.700595,55.749435,28,0,10.0,1,301175786,34.0,6,20.0,18990000
4,4,1,37.696511,55.753244,11,0,13.2,1,301392165,38.9,3,12.7,12436330